PV de l'assemblée générale du 25/04/2020
Infobourg/docs pull request #2
Opened 2020-04-27 16:32 UTC by IliasRedissi

Ordre du jour :
- Fixation du montant des cotisations
- Présentation des activités effectuées et projets futurs
- Approbation du budget de l’association pour l’exercice en cours
- Débat sur la modification du règlement intérieur
- Renouvellement des membres du conseil d’administration
- Questions diverses

TODO : 
[ ] Compte de résultat
[ ] Liste des candidats pour le conseil d’administration

2020-04-27 16:37 UTC, aturlier requested changes

2020-04-27 16:37 UTC, aturlier commented on Procès-Verbaux/PV_2020_04_25_AG_1.md
> +Le premier événements crée au nom de l'association fut le #slack_irl 2. Ce qui a été retenu de cette événements est qu'il y a eu une meilleure organisation : temps d'organiser plus court, pizza compr
```suggestion
Le premier événement crée au nom de l'association fut le #slack_irl 2. Ce qui a été retenu de cette événements est qu'il y a eu une meilleure organisation : temps d'organiser plus court, pizza comprise avec une formule entreprise.
```

2020-04-27 16:37 UTC, aturlier commented on Procès-Verbaux/PV_2020_04_25_AG_1.md
> +Des membres du bureau ont discuté avec l'association Entour'âge Solidaire concernant un éventuel partenariat. L'idée serait de proposer des formations/présentation à un public à la fois jeune et séni
```suggestion
Des membres du bureau ont discuté avec l'association Entour'âge Solidaire concernant un éventuel partenariat. L'idée serait de proposer des formations/présentations à un public constitué à la fois de jeunes et de séniors.
```

2020-04-27 16:39 UTC, aturlier approved these changes
PV approuvé

2020-04-29 05:38 UTC, Milihhard commented on Procès-Verbaux/PV_2020_04_25_AG_1.md
> +Thibault Laperrière et Emilien Nicolas ont présenté le bilan et le compte de résultat sur la période du 30/09/2019 au 31/03/2020. Les documents sont disponibles en annexe.
Where is the annexe?

2020-04-30 12:06 UTC, IliasRedissi commented on Procès-Verbaux/PV_2020_04_25_AG_1.md
> +Thibault Laperrière et Emilien Nicolas ont présenté le bilan et le compte de résultat sur la période du 30/09/2019 au 31/03/2020. Les documents sont disponibles en annexe.
Tous les documents ont été ajoutés

2020-04-30 12:50 UTC, Daffyfrog approved these changes
Approved

2020-04-30 12:50 UTC, merged