Added release workflow
Infobourg/docs pull request #6
Opened 2020-06-02 12:56 UTC by aturlier

✨

2020-06-02 13:46 UTC, IliasRedissi submitted a review, later dismissed

2020-06-02 13:57 UTC, Milihhard submitted a review, later dismissed

2020-07-04 18:26 UTC, IliasRedissi requested changes

2020-07-04 18:26 UTC, IliasRedissi commented on .github/workflows/release.yml
> +description: Creates a release on tag & upload pdfs
```suggestion
name: Creates a release on tag & upload pdfs
```

2020-07-16 15:09 UTC, IliasRedissi approved these changes

2021-04-07 16:06 UTC, merged